feate: init
smartxworks/cluster-api-provider-elf pull request #1
Opened 2021-06-09 07:28 UTC by haijianyang

TODO
1. 测试
2. 镜像打包
3. 目前只完成了主流程，一些细节需要继续完善，比如虚拟机创建失败怎么处理等。

2021-06-10 04:10 UTC, fengye87 requested changes

2021-06-10 04:10 UTC, fengye87 commented on pkg/service/secret.go
> +type SecretService interface {
和 ClusterService 同样问题

2021-06-10 04:10 UTC, fengye87 commented on pkg/service/node.go
> +type NodeSrevice interface {
和 ClusterService 同样问题

2021-06-10 04:10 UTC, fengye87 commented on pkg/service/vm.go
> +type VmService interface {
关于接口和实现，通常我们倾向把接口定义在使用侧，也就是哪里需要这个接口，定义在哪里。另外实现的类命名不要使用 XxxImpl，可以是例如 ElfVMService 之类，表示明确的基于什么的实现。

2021-06-10 04:10 UTC, fengye87 commented on pkg/service/vm.go
> +func (svr *VmServiceImpl) GetTpl(tplId string) (*client.VmTemplate, error) {
template 的常见缩写不是 tpl，而是 tmpl，以及建议这种就不要缩写了，特别是函数名。

2021-06-10 04:10 UTC, fengye87 commented on pkg/service/vm.go
> +func ToVirtualMachine(elfVm *client.Vm) *infrav1.VirtualMachine {
VM 倒是可以缩写

2021-06-10 04:10 UTC, fengye87 commented on pkg/session/kube.go
> +func NewKubeClient(
这个 vmware provider 是放在 util 里面的，我们放这里有什么考虑么？

2021-06-10 04:10 UTC, fengye87 commented on pkg/util/machine.go
> +package util
文件名还是叫 machines.go 比较合理

2021-06-10 04:16 UTC, fengye87 commented
看到比较多的地方是借鉴 vmware provider 的代码组织和实现的，这个在我们初步上马的阶段是完全没问题的，但建议遵循两点要求：

1. 必须完全掌握和理解每行代码的作用
2. 没有充分的理由前不要做我们自己的额外发挥

2021-06-10 04:18 UTC, fengye87 commented
另外，commit message 有问题。简单一点的 commit message 要求可以看 https://chris.beams.io/posts/git-commit/ ，这是必须要满足的。要求高一点的 commit message 可以看 https://udacity.github.io/git-styleguide/ ，不做强制要求

2021-06-10 07:45 UTC, haijianyang commented on pkg/session/kube.go
> +func NewKubeClient(
KubeClient 和 ElfClient 应该是类似的，都是建立和其它客户度的连接。

2021-06-10 07:48 UTC, haijianyang commented on api/v1alpha3/elfmachine_types.go
> +	VmRef string `json:"vmRef,omitempty"`
最开始放在了 status，后面看到 yiran 和 vmware provider 都放在了 spec，就挪了过去。

2021-06-10 07:50 UTC, haijianyang commented on go.mod
> +	sigs.k8s.io/controller-runtime v0.5.14
vsphere 和 AWS 都用了这个版本，保持跟 cluster-api 使用的 controller-runtime 保持一致。

2021-06-10 07:51 UTC, haijianyang commented on go.mod
> +	k8s.io/client-go v0.17.9
同样跟 vsphere 和 AWS 他们最新发布的版本保持一致。

2021-06-10 15:29 UTC, haijianyang commented on pkg/manager/manager.go
> +func newClientFunc(cache cache.Cache, config *rest.Config, options client.Options) (client.Client, error) {
这个参数的类型就是 NewClientFunc，一个函数定义。

2021-06-10 15:30 UTC, haijianyang commented on pkg/record/recorder.go
> +package record
这样可能会引入 capv 其他不需要的代码。

2021-06-11 01:18 UTC, fengye87 commented on api/v1alpha3/elfmachine_types.go
> +	VmRef string `json:"vmRef,omitempty"`
vmware provider 那边我似乎没看到这个字段

2021-06-11 01:51 UTC, haijianyang commented on api/v1alpha3/elfmachine_types.go
> +	VmRef string `json:"vmRef,omitempty"`
vmware 版本2的时候叫 MachineRef，现在版本三改成了 BiosUUID

2021-06-11 07:28 UTC, haijianyang commented on pkg/manager/manager.go
> +func newClientFunc(cache cache.Cache, config *rest.Config, options client.Options) (client.Client, error) {
发现 cluster-api 已经提供了这个函数 ManagerDelegatingClientFunc，我换成这个。

2021-06-11 07:29 UTC, haijianyang commented on pkg/record/recorder.go
> +package record
暂时把这部分代码移除，目前可以不用。

2021-06-16 08:08 UTC, fengye87 requested changes

2021-06-16 08:08 UTC, fengye87 commented on controllers/elfcluster_controller.go
> +	clusterService := service.NewClusterSrevice(r.Client)
NewClusterSrevice 中的 srevice 是 typo，把几处 typo 都更正下

2021-06-16 08:08 UTC, fengye87 commented on go.mod
> +	sigs.k8s.io/controller-runtime v0.5.14
我们看到 vsphere 用的是最新的 v0.9.0-alpha.1

2021-06-16 08:08 UTC, fengye87 commented on go.mod
> +	k8s.io/client-go v0.17.9
我看到 vsphere 用的是最新的 v0.21.0-beta.1

2021-06-16 08:08 UTC, fengye87 commented on pkg/service/cluster.go
> +func NewClusterSrevice(client client.Client) *ClusterSrevice {
这个问题上次讨论的结论应该是没必要抽象成一个 interface？machine service 也是同理？

2021-06-16 08:09 UTC, fengye87 commented
另外，不要 force push，会造成我 review 的历史被破坏

2021-06-17 03:34 UTC, haijianyang commented on go.mod
> +	sigs.k8s.io/controller-runtime v0.5.14
之前只是参考了稳定版本，我看下 Alpha 和 Beta 版本。

2021-06-17 03:34 UTC, haijianyang commented on go.mod
> +	k8s.io/client-go v0.17.9
👌🏻

2021-06-17 03:34 UTC, haijianyang commented on pkg/session/kube.go
> +func NewKubeClient(
👌🏻

2021-06-17 03:35 UTC, haijianyang commented on README.md
> +export ELF_SERVER_PASSWORD=root
好

2021-06-17 03:40 UTC, haijianyang commented on pkg/service/cluster.go
> +func NewClusterSrevice(client client.Client) *ClusterSrevice {
这里指的是 cluster service 和 machine service 删除，直接使用 client.get 这样？

2021-06-17 03:56 UTC, haijianyang commented on go.mod
> +	sigs.k8s.io/controller-runtime v0.5.14
最新的稳定版本是 https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/v0.7.8

2021-06-17 11:40 UTC, haijianyang commented on api/v1alpha3/elfmachine_types.go
> +	VmRef string `json:"vmRef,omitempty"`
没有得到 VMRef 放在哪里的结论，先放到 status。

2021-06-17 12:10 UTC, haijianyang commented on pkg/service/machine.go
> +type MachineSrevice interface {
已删除

2021-06-17 12:10 UTC, haijianyang commented on pkg/service/cluster.go
> +type ClusterSrevice interface {
已删除

2021-06-22 02:07 UTC, fengye87 requested changes

2021-06-22 02:07 UTC, fengye87 commented on controllers/elfcluster_controller.go
> +	if err := r.Client.Get(r, req.NamespacedName, elfCluster); err != nil {
这里的写法建议是

```go
var elfCluster infrav1.ElfCluster
if err := r.Client.Get(r, req.NamespacedName, &elfCluster); ...
```

这样比较明显的表示 Get 这个函数会初始化 elfCluster。同样道理的，例如 json.Unmarshal 也推荐这么写。类似地方建议都改一下

2021-06-22 02:07 UTC, fengye87 commented on go.mod
> +	k8s.io/client-go v0.17.9
这里的版本还是没有更新？

2021-06-22 07:10 UTC, haijianyang commented on go.mod
> +	k8s.io/client-go v0.17.9
上次说的应该是参照 vsphere 最新稳定版本？
vsphere 最新版本的依赖：
	github.com/go-logr/logr v0.4.0
	github.com/onsi/ginkgo v1.12.1
	github.com/onsi/gomega v1.10.1
	github.com/pkg/errors v0.9.1
	k8s.io/api v0.17.9
	k8s.io/apiextensions-apiserver v0.17.9
	k8s.io/apimachinery v0.17.9
	k8s.io/client-go v0.17.9
	k8s.io/klog v1.0.0
	sigs.k8s.io/cluster-api v0.3.14
	sigs.k8s.io/controller-runtime v0.5.14

2021-06-22 07:11 UTC, haijianyang commented on controllers/elfcluster_controller.go
> +	if err := r.Client.Get(r, req.NamespacedName, elfCluster); err != nil {
👌🏻

2021-06-22 08:10 UTC, haijianyang commented on controllers/elfcluster_controller_test.go
> +			Expect(reconciler.Client.Get(reconciler, elfClusterKey, elfCluster)).To(Succeed())
@fengye87 
这里用不用改成这样的形式，这里用的是全局的 var elfCluster  *infrav1.ElfCluster
var elfCluster infrav1.ElfCluster
if err := r.Client.Get(r, req.NamespacedName, &elfCluster); ...

2021-06-28 06:31 UTC, haijianyang commented
1.重构 config ：https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html#refactor-kustomize-config-folder-to-support-multi-tenancy-when-using-webhooks
2.支持 clusterctl：https://cluster-api.sigs.k8s.io/clusterctl/configuration.html、https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html

2021-06-30 11:33 UTC, haijianyang commented
使用 kube-vip 作为 HA 和 LB 方案 https://kube-vip.io

2021-07-01 09:30 UTC, haijianyang commented
增加 e2e 测试，待 CI 加入 e2e 测试。

2021-07-02 05:51 UTC, fengye87 approved these changes

2021-07-02 05:51 UTC, fengye87 commented
@haijianyang 改下 PR 的 title

2021-07-02 06:35 UTC, haijianyang commented on controllers/elfcluster_controller_test.go
> +			Expect(reconciler.Client.Get(reconciler, elfClusterKey, elfCluster)).To(Succeed())
vmware 和 AWS 都是用这种方式：
elfCluster := &infrav1.ElfCluster{}
	if err := r.Client.Get(r, req.NamespacedName, elfCluster); err != nil {}

2021-07-02 06:44 UTC, haijianyang commented on Makefile
> +	source ./hack/fetch_ext_bins.sh; fetch_tools; setup_envs; go test -v ./api/... ./controllers/... ./pkg/... -coverprofile cover.out
wmware 和 AWS 都不用 setup-envtest.sh 了，使用 fetch_ext_bins.sh 代替。fetch_ext_bins 提前写好了测试环境准备的代码，setup-envtest.sh 需要动态去下载代码。

2021-07-02 07:05 UTC, fengye87 commented
@haijianyang 这个 title 会变成最终的 commit message，请按照 commit message 的要求修改

2021-07-05 01:47 UTC, fengye87 commented
@haijianyang 这个 title 还是不好，首先这个不一定就是 0.1.0，其次也没有实际描述做了什么

2021-07-05 10:14 UTC, haijianyang commented
ElfMachine 加入 conditions 
- https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200506-conditions.md
- https://github.com/kubernetes-sigs/cluster-api/tree/master/test/infrastructure/docker/controllers

2021-07-06 03:41 UTC, merged