Change Elf SDK to Tower SDK
smartxworks/cluster-api-provider-elf pull request #7
Opened 2021-09-14 11:05 UTC by haijianyang

@fengye87 

1. 切换到 Tower SDK（SDK 目前还不是稳定版）
2. 目前还没有稳定的可以跑 E2E 的 Tower 环境（503、无法删除虚拟机等）
3. Tower 目前会遇到 IP 同步不及时（可能十几分钟）

2021-09-15 01:39 UTC, fengye87 requested changes

2021-09-15 01:39 UTC, fengye87 commented on pkg/config/vm.go
> +	VMPassword    = "HC!r0cks"
这个换一个值吧

2021-09-15 10:43 UTC, haijianyang commented on pkg/config/vm.go
> +	VMPassword    = "HC!r0cks"
换成哪种风格的呢

2021-09-16 08:15 UTC, fengye87 commented on pkg/config/vm.go
> +	VMPassword    = "HC!r0cks"
随便，别是这个就行

2021-09-22 07:02 UTC, haijianyang commented
VM 的密码改成虚拟机模板设置的密码。

2021-09-22 07:07 UTC, haijianyang commented on test/fake/tower.go
> +func NewTowerVM() *models.VM {
嗯这里需要改一下，现在用了 Tower SDK，默认应该就是 Tower 的虚拟机了。

2021-09-22 07:24 UTC, fengye87 commented on test/fake/tower.go
> +func NewTowerVM() *models.VM {
没必要吧，以前也不叫 NewElfVM 啊

2021-09-22 07:45 UTC, haijianyang commented on test/fake/tower.go
> +func NewTowerVM() *models.VM {
嗯嗯，我的意思是要去掉“tower”这个命名前缀（没有表达清楚）。之前的话在 CAPE 确实定义了一些 VM，Job 之类的，为了区别 Elf VM。

2022-05-12 08:26 UTC, closed without merging